import{a as L,S,i as l}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const w="52822866-647b6b4c94b7d4074c4dcbe1c",q=L.create({baseURL:"https://pixabay.com/api/"});async function P(r,e){const{data:i}=await q.get("/",{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});return i}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".js-load-more"),v=new S(".gallery a",{captionsData:"alt",captionDelay:250});function E(r){const e=r.map(({webformatURL:i,largeImageURL:a,tags:t,likes:o,views:s,comments:p,downloads:b})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${i}" alt="${t}" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${s}</li>
          <li><b>Comments:</b> ${p}</li>
          <li><b>Downloads:</b> ${b}</li>
        </ul>
      </li>`).join("");u.insertAdjacentHTML("beforeend",e),v.refresh()}function $(){u.innerHTML=""}function R(){f.classList.remove("is-hidden")}function M(){f.classList.add("is-hidden")}function O(){m.classList.remove("is-hidden")}function c(){m.classList.add("is-hidden")}const h=document.querySelector(".form"),x=document.querySelector(".js-load-more");let y="",n=1;const B=15;let d=0;h.addEventListener("submit",A);x.addEventListener("click",j);function j(){n+=1,g().then(()=>{const r=document.querySelector(".gallery-item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})})}function A(r){r.preventDefault();const e=h.elements["search-text"].value.trim();if(!e){l.warning({message:"Please enter a search query.",position:"topRight"});return}y=e,n=1,d=0,c(),$(),g()}async function g(){var r;R();try{const e=await P(y,n);if(n===1&&(d=e.totalHits),!((r=e.hits)!=null&&r.length)){n===1&&l.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c();return}E(e.hits),n*B<d?O():(c(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{M()}}
//# sourceMappingURL=index.js.map
